### ISSUE TITLE
Load measure from file tab has a different effect than load from the button next to save button

### ISSUE THREAD

**Issue by leghtas** [Exopy/exopy#101]
When loading a measure by clicking file -- load measure, a new measure tab is created. This is fine.
However, when instead we load a measure by clicking on the load button next to the save button, this replaces the currently opened measure, rather than creating a new tab.

**Comment by MatthieuDartiailh** [comment]
This is actually what I coded. If you find that behavior confusing we can change it. What do you suggest ?

**Comment by leghtas** [comment]
I see, so I think that button should just be removed, since there is a risk of loosing edits on the measure.

**Comment by MatthieuDartiailh** [comment]
I am myself not against this change, any comments @lcontami or @tcubaynes ? Anyway feel free to open a PR @leghtas.

**Comment by lcontami** [comment]
I don't have a strong opinion. I think it is nice to have a shortcut to load; the button could also have the same behavior as file > load. It's just not very clean then to have this "M001" empty measure that's going to stay in the tabs but it will also be the case if the button is simply supressed.

**Comment by MatthieuDartiailh** [comment]
@leghtas can we close this or do you plan to change this behavior ?

**Comment by MatthieuDartiailh** [comment]
We consider this is working as expected closing.
