### ISSUE TITLE
Make a first release before removing Python 2

### ISSUE THREAD

**Issue by MatthieuDartiailh** [Exopy/exopy#115]
I plan to clean a bit the test system (inspired by some work I did on enaml) and I will take advantage of this to remove all mentions of Python 2 compatibility (from the code and from the docs). As it may cause some issues to some people it would be best to get the 0.1.0 out first.

Is there any outstanding issue you would like to see fixed before @Ecpy/owners ?

**Comment by MatthieuDartiailh** [comment]
Do the people in Lyon have an opinion on this ? @ncottet, @bhuard

**Comment by Qcircuits** [comment]
I have no idea what you're talking about. What is the 0.1.0?
We agree that ecpy is not compatible with Python 2 anyway right?
Benjamin

**Comment by MatthieuDartiailh** [comment]
For the time being ecpy supports Python 2. The idea is yo reduce the maintenance burden by only supporting Python 3.5 and 3.6 in the future. So I was suggesting to tag a release (version number 0.1.0) that would be the last to support Python 2 before cleaning up the codebase. If you are already working with Python 3, this won't have any impact on you.

**Comment by bhuard** [comment]
Ok great!

**Comment by ncottet** [comment]
We have been using Python 3 for Ecpy from the beginning so this will definitely not impact us. I think what you propose is the best way to do it.

**Comment by MatthieuDartiailh** [comment]
Ok thanks. I will do this when I can find some time to do so then.

**Comment by MatthieuDartiailh** [comment]
Done
