### ISSUE TITLE
Task tree: Double click to rename issue

### ISSUE THREAD

**Issue by rassouly** [Exopy/exopy#143]
Currently it is possible to rename one task in the tree by double clicking on it. This breaks the naming convention e.g. it is possible to rename `test(exopy_hqc_legacy.ApplyMagFieldTask)` into `test`. This might lead to other issues.
This issue doesn't exist when I use right-click->rename.

Solution: Double click to rename should be disabled or fixed to behave light right-click->rename.

**Comment by MatthieuDartiailh** [comment]
Why did you close ?

**Comment by rassouly** [comment]
I was unable to reproduce the bug a second time.
Double click to rename behaves differently : renaming starts from the full name (user name + class) instead of just the user name but it does append the class name at the end as it should.

**Comment by MatthieuDartiailh** [comment]
Still it means there is something off, and worth fixing at a point.
