### ISSUE TITLE
Using instrument drivers outside of a measurement

### ISSUE THREAD

**Issue by rassouly** [Exopy/exopy#169]
I am currently adding a feature to a task that requires using the driver when editing the measurement (before the measurement is enqueued). However, AFAIK, there is no way to initialize the driver from inside a task. For example start_driver() fails because root.run_time is not initialized at this point. I have resorted to talking manually to the instrument inside of the task which is far from optimal.
Communicating with instruments during measurement editing could be useful to add quality of life features to exopy: live display of current instrument settings, dry runs for pulse generators (the feature I am currently adding), one click setting of a voltage/frequency/power without running a full blown measurement, ...
I don't really know I would go about implementing such a feature however. Any ideas? Is issue #91 related?

**Comment by MatthieuDartiailh** [comment]
You can have a look at the `test_driver` method of `InstrTask`. It provides a context manager to access in a temporary to a driver. I can see the need for this during edition for things with a complex configuration.
The idea of one-click setting is strongly reminiscent of the idea of having a control panel. This is no small work to get together and would be better based from i3py. If you are interested in picking that up we could Skype this week.

**Comment by rassouly** [comment]
I've looked at test_driver before but looking at the code, this is basically the same method as start_driver with some try block around it (and a driver.stop() at the end). In my case, since self.root.run_time is None, an exception is triggered and the driver returned is None as well.

> The idea of one-click setting is strongly reminiscent of the idea of having a control panel. This is no small work to get together and would be better based from i3py. 

I unfortunately don't have the time right now but the idea sounds nice.

**Comment by MatthieuDartiailh** [comment]
Sorry my bad, I was thinking about this TODO in the instrument view `# TODO add a context manager allowing to get a temporary access to a driver` and I never did implement it.

To do that properly you need to request the profile from the instrument plugin since a running measurement may be using it. We can Skype to discuss the details if you want.

**Comment by rassouly** [comment]
> To do that properly you need to request the profile from the instrument plugin since a running measurement may be using it.

I'm trying to do this but I can't find a way to get the plugin from within `InstrTask`. I don't seem to have access to the workbench...

**Comment by MatthieuDartiailh** [comment]
Do it from the view, not the task.

**Comment by rassouly** [comment]
> Do it from the view, not the task.

Thanks, I can get access to the plugin now, I'll be submitting a patch soon.

**Comment by MatthieuDartiailh** [comment]
Closed by #172
